name: CrimeDetection-app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start the app
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=production
          flask run --host=0.0.0.0 --port=5000
        env:
          PORT: 'AppSecretKey'
